### ISSUE TITLE
Available component "+" and "-" button issue.

### ISSUE THREAD

**Issue by henrywang** [weldr/cockpit-composer#216] opened 2018-03-23 02:10 UTC
### Description of problem
The available component add or remove button should be constant after clicking Discard Changes

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
ac8be5731024b3fcf54f1da73565dedd505253a0

### How often reproducible
100%

### Steps to Reproduce

1. go to edit blueprint page.
2. make a component change.
3. click discard changes button.

### Actual results
The "+" should be "+" and "-" should be "-".
### Expected results
All "-" button changed to "+".

**Comment by atodorov** [comment] 2018-04-24 08:39
From what I can tell "Discard changes" doesn't really discard anything. Maybe that's the problem.

**Comment by jgiardino** [comment] 2018-06-26 21:02
I'm not able to reproduce this issue.

**Comment by KKoukiou** [comment] 2019-04-25 12:02
Indeed I confirm that this issue is not reproducable. @henrywang please verify as well and close the issue if not more applicable.

**Closed** 2019-05-24 15:36 UTC
